#!/bin/bash
set -e

OS=unix
BINEXT=
ARTEFACT_OS=linux
ARTEFACT_EXT=.tar.gz
ARCH=x64
if [[ "$OSTYPE" == "cygwin" || "$OSTYPE" == "msys" ]]; then
    OS=windows
    BINEXT=.exe
    ARTEFACT_OS=win
    ARTEFACT_EXT=.zip
elif [[ -f "/etc/alpine-release" ]]; then
    ARTEFACT_OS=musl
fi

if [ "$CONFIGURATION" = "" ]; then
    CONFIGURATION=Release
fi

VCPKG_TRIPLET_ARG=""
VCPKG_TOOLCHAIN_ARG=""
if [ "$STATIC" == "true" ]; then
    VCPKG_TRIPLET_ARG="-DVCPKG_TARGET_TRIPLET=x64-windows-static"
fi
if [ "$OS" == "windows" ]; then
    VCPKG_TOOLCHAIN_ARG="-DCMAKE_TOOLCHAIN_FILE=$VCPKG_LOCATION"
fi

VCPKG_LOCATION=M:/git/vcpkg/scripts/buildsystems/vcpkg.cmake
CMAKE_CLEAN="rm -rf bin out"
CMAKE_CONFIGURE_CMD="cmake -G Ninja -B bin -DCMAKE_BUILD_TYPE=$CONFIGURATION $VCPKG_TRIPLET_ARG $VCPKG_TOOLCHAIN_ARG"
CMAKE_BUILD_CMD="cmake --build bin"
CMAKE_INSTALL_CMD="cmake --install bin"

archive() {
    mkdir -p artefacts
    pushd "$2" > /dev/null
        rm -f "../artefacts/$1"
        if [[ "$OSTYPE" == "cygwin" || "$OSTYPE" == "msys" ]]; then
            7z a -y -bd -r "../artefacts/$1" ./*
        else
            tar -czf "../artefacts/$1" *
        fi
    popd > /dev/null
}

echo -e "\033[0;36mBuilding libsawyer\033[0m"
$CMAKE_CLEAN
$CMAKE_CONFIGURE_CMD
$CMAKE_BUILD_CMD
$CMAKE_INSTALL_CMD
archive "libsawyer-$ARTEFACT_OS-$ARCH$ARTEFACT_EXT" out

if [ "$OS" != "windows" ] || [ "$STATIC" = "true" ]; then
    echo -e "\033[0;36mBuilding fsaw\033[0m"
    pushd tools/fsaw > /dev/null
        $CMAKE_CLEAN
        $CMAKE_CONFIGURE_CMD
        $CMAKE_BUILD_CMD
    popd > /dev/null

    echo -e "\033[0;36mBuilding spritec\033[0m"
    pushd tools/spritec > /dev/null
        $CMAKE_CLEAN
        $CMAKE_CONFIGURE_CMD
        $CMAKE_BUILD_CMD
    popd > /dev/null

    mkdir -p temp
    cp "tools/fsaw/bin/fsaw$BINEXT" temp
    cp "tools/spritec/bin/spritec$BINEXT" temp
    archive "libsawyer-tools-$ARTEFACT_OS-$ARCH$ARTEFACT_EXT" temp
    rm -rf temp
fi
