name: CI
on: [push, pull_request]
jobs:
  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Prepare environment
        run: |
          sudo apt-get install libgtest-dev ninja-build

      - name: Checkout
        uses: actions/checkout@v1
      - name: Build libsawyer
        run: |
          cmake -G Ninja -B bin -DCMAKE_BUILD_TYPE=Release
          cmake --build bin
          cmake --install bin

      - name: Test libsawyer
        run: |
          cmake --build bin --target tests
          bin/tests

      - name: Build fsaw
        run: |
          cd tools/fsaw
          cmake -B bin
          cmake --build bin
