name: CI
on: [push, pull_request]
jobs:
  alpine:
    name: Alpine
    runs-on: ubuntu-latest
    container: alpine
    strategy:
      fail-fast: false
      matrix:
        platform: [x64]
    steps:
      - name: Prepare environment
        run: apk add bash cmake ninja g++ libpng-dev nlohmann-json gtest-dev
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build libsawyer
        run: ./build libsawyer
      - name: Test libsawyer
        run: ./run-tests
      - name: Build fsaw
        run: ./build fsaw
      - name: Build spritec
        run: ./build spritec
      - name: Package tools
        run: ./build tools
      - name: Upload tools
        uses: actions/upload-artifact@v3
        with:
          name: libsawyer-tools-musl-${{ matrix.platform }}.tar.gz
          path: artefacts/libsawyer-tools-musl-${{ matrix.platform }}.tar.gz
  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [x64]
    steps:
      - name: Prepare environment
        run: sudo apt-get install ninja-build libpng-dev nlohmann-json3-dev libgtest-dev
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build libsawyer
        run: ./build libsawyer
      - name: Test libsawyer
        run: ./run-tests
      - name: Build fsaw
        run: ./build fsaw
      - name: Build spritec
        run: ./build spritec
      - name: Package tools
        run: ./build tools
      - name: Upload tools
        uses: actions/upload-artifact@v3
        with:
          name: libsawyer-tools-linux-${{ matrix.platform }}.tar.gz
          path: artefacts/libsawyer-tools-linux-${{ matrix.platform }}.tar.gz

  windows-shared:
    name: "Windows[shared]"
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        - platform: x86
          arch: x86
        - platform: x64
          arch: amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache vcpkg
        uses: actions/cache@v3
        env:
          cache-name: cache-vcpkg
        with:
          path: C:/vcpkg
          key: ${{ runner.os }}-build-${{ env.cache-name }}
      - name: Build libsawyer
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" -arch=${{ matrix.arch }}
          sh build libsawyer
      - name: Test libsawyer
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" -arch=${{ matrix.arch }}
          sh run-tests
      - name: Upload zip as artifact
        uses: actions/upload-artifact@v3
        with:
          name: libsawyer-win-${{ matrix.platform }}.zip
          path: artefacts/libsawyer-win-${{ matrix.platform }}.zip
  windows-static:
    name: "Windows[static]"
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        - platform: x86
          arch: x86
        - platform: x64
          arch: amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache vcpkg
        uses: actions/cache@v3
        env:
          cache-name: cache-vcpkg
        with:
          path: C:/vcpkg
          key: ${{ runner.os }}-build-${{ env.cache-name }}
      - name: Build libsawyer
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" -arch=${{ matrix.arch }}
          sh build libsawyer --static
      - name: Build fsaw
        if: matrix.platform == 'x64'
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" -arch=${{ matrix.arch }}
          sh build fsaw --static
      - name: Build spritec
        if: matrix.platform == 'x64'
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" -arch=${{ matrix.arch }}
          sh build spritec --static
      - name: Package tools
        if: matrix.platform == 'x64'
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" -arch=${{ matrix.arch }}
          sh build tools --static
      - name: Upload libsawyer
        uses: actions/upload-artifact@v3
        with:
          name: libsawyer-win-${{ matrix.platform }}-static.zip
          path: artefacts/libsawyer-win-${{ matrix.platform }}-static.zip
      - name: Upload tools
        if: matrix.platform == 'x64'
        uses: actions/upload-artifact@v3
        with:
          name: libsawyer-tools-win-${{ matrix.platform }}.zip
          path: artefacts/libsawyer-tools-win-${{ matrix.platform }}.zip
